version: '3.8'
services:
  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    command: -jar DynamoDBLocal.jar -inMemory -sharedDb
  app-node:
    depends_on:
      - dynamodb-local
    build:
      context: .
      dockerfile: ./src/main/docker/Dockerfile.jvm
    container_name: app-node
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      QUARKUS_DYNAMODB_ENDPOINT_OVERRIDE: http://dynamodb-local:8000/
      AWS_ACCESS_KEY_ID: sample-key
      AWS_SECRET_ACCESS_KEY: sample-secret
    links:
      - "dynamodb-local"
